; SideMon CYD receiver firmware
; ESP32 + ILI9341 (Cheap Yellow Display)
[env:cyd]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    bodmer/TFT_eSPI
    bblanchon/ArduinoJson
build_flags =
    -DUSER_SETUP_LOADED=1
    -DILI9341_2_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DMOSI_PIN=13
    -DMISO_PIN=12
    -DSCLK_PIN=14
    -DTFT_CS_PIN=15
    -DTFT_DC_PIN=2
    -DTFT_RST_PIN=-1
    -DTFT_BL_PIN=21
    -DSPI_FREQUENCY=55000000
    -DSPI_READ_FREQUENCY=20000000
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_FONT6=1
    -DLOAD_FONT7=1
    -DLOAD_FONT8=1
    -DSMOOTH_FONT=1
    -DSIDEMON_DEFAULT_SSID="\"SSID\""
    -DSIDEMON_DEFAULT_PASS="\"PASSWORD\""
    -DSIDEMON_DEFAULT_PORT=9877
